# Arquivo de configuração de TMUX
# Salvar como: ~/.config/tmux/tmux.conf
# Autor: Helio Giroto


# Mudar o prefixo para Ctrl+a
# muda a tecla de prefixo para control + espaço:
set -g prefix C-Space
# libera control + b para outras funções, se quiser:
unbind C-b
# caso se usa control + espaço em outros programas ou sistema, basta pressioná-lo 2 vezes e ele funciona normalmente:
bind C-Space send-prefix


# outras configurações:
# dividir janelas de forma inteligente: 
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# habilitar mouse: 
set -g mouse on

# aumentar histórico de scroll: 
set -g history-limit 10000


# Barra de Status Personalizada:
set -g status-bg colour25
set -g status-fg colour253
set -g status-right "#[fg=colour253]%d/%B/%Y - %R "

# ver cores.py

