let anterior = -1;
let atual = 0;
let contatos = [];
let padrao = /^\+/;
const seletorCaptura = 'div[role="gridcell"] > div > div > span';
const d = new Date();
let dia = d.getDay();
if (dia < 10) dia = `0${dia}`;
let mes = d.getMonth()+1;
if (mes < 10) mes = `0${mes}`;
let ano = d.getFullYear();
let dataAtual = `${ano}${mes}${dia}`;
let hora = d.getHours();
let minuto = d.getMinutes();
if (minuto < 10) minuto = `0${minuto}`;
let horaAtual = `${hora}:${minuto}`;
